### PR TITLE
v1.0.2

### PR DESCRIPTION
**Pull request by mallex-actee**
* Adding bump scripts

* patch version

### CODE REVIEW

**Comment by enys** [comment]
@maxime-allex how did you trigger this ? manually ? the version does not match.
The rest looks good though

**Comment by mallex-actee** [comment]
I triggered a bump manually yes since it was not done from the CI. Should I revert?

**Comment by enys** [comment]
That's fine for now, but perhaps change the title to v1.0.2 ?

**Review by enys — APPROVED** [review]
Pending change of title, to 1.0.2, but LGTM

**Pull request merged**
